let g:ale_disable_lsp = 0
let g:ale_echo_delay = 100
let g:ale_lint_delay = 1000
let g:ale_echo_msg_format = '%linter%: %code: %%s [%severity%]'
let g:ale_history_enabled = 0
let g:ale_sign_error = '✖'
let g:ale_sign_warning = 'ⁱ'
let g:ale_maximum_file_size = 500000
" let g:ale_linters = {'go': ['golangci-lint']}
